DECLARE @CHINCHO TABLE(
	Full_Name VARCHAR(MAX),
	BirthDate VARCHAR(MAX)
);

INSERT INTO @CHINCHO
SELECT
	FirstName +' '+ LastName,
	CAST(BirthDate AS VARCHAR(MAX))
FROM Employees;

INSERT INTO @CHINCHO VALUES 
('NIKA', '2012-01'),
('LADO', '2022-12-01'),
('LAZVI', '20-1567'),
('LERI', '58-75-01'),
('CHAKVE', '2012-01-23');

SELECT 
	*,
	ISDATE(BirthDate) AS CHECKS_IF_DATE
FROM @CHINCHO;