
ALTER TABLE OrderDetails ADD CONSTRAINT FK_OrderID FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE OrderDetails ADD CONSTRAINT FK_ProductID FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Orders ADD CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE Orders ADD CONSTRAINT FK_EmployeeID FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE Orders ADD CONSTRAINT FK_ShipperID FOREIGN KEY (ShipperID) REFERENCES Shippers(ShipperID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE ProductCost ADD CONSTRAINT FK_Product_CostID FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE Products ADD CONSTRAINT FK_Supplier_product_ID FOREIGN KEY (SupplierID) REFERENCES Suppliers(SupplierID) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE Products ADD CONSTRAINT FK_Category_product_ID FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON UPDATE NO ACTION ON DELETE NO ACTION;
